curators:
 - alexellis

features:
 - dco_check
 - comments
 - pr_description_required
# - hacktoberfest
 - release_notes

contributing_url: https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md
